---
- hosts: production

  tasks:
  - name: Install Zabbix repo
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
          tags:
      - zabbix-repo

#This works if Zabbix repo is installed (see previous task)
#rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  - name: Install Zabbix agent
    yum:
      name: zabbix-agent
      state: present
    tags:
      - zabbix-agent

  - name: Zabbix agent server in conf
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: Server=10.10.100.250
    tags:
      - zabbix-conf

  - name: Enable and start Zabbix agent service
    systemd:
      name: zabbix-agent
      state: started
      enabled: yes
    tags:
      - zabbix-service

